# Pull gems from RubyGems
source 'https://rubygems.org'
gem "sass", "~>3.3"
gem "compass", "~>1.0.3"
gem 'singularitygs', '~>1.6.2'
gem 'breakpoint', '~>2.4'
gem 'compass-normalize', '~>1.5'
gem 'json', '~>1.8.3'
